# Generated by Django 4.0.4 on 2022-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('summer_clothes', 'Summer_Clothes'), ('winter_clothes', 'Winter_Clothes'), ('rainy_clothes', 'Rainy_Clothes'), ('wedding_clothes', 'Wedding_Clothes'), ('holidays_clothes', 'Holidays_Clothes')], default='rainy_clothes', max_length=100)),
                ('images', models.ImageField(upload_to='clothes/')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('manufacture_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('television', 'Television'), ('laptop', 'Laptop'), ('personal_computer', 'Personal_Computer'), ('fan', 'Fan'), ('lights', 'Lights')], default='laptop', max_length=100)),
                ('images', models.ImageField(upload_to='electronics/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('manufacture_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('washimg_machine', 'Washing_Machine'), ('refrigerator', 'Refrigerator'), ('water_heater', 'Water_Heater'), ('micro_oven', 'Micro_Oven'), ('dish_washer', 'Dish_Washer')], default='washimg_machine', max_length=100)),
                ('images', models.ImageField(upload_to='home_appliances/')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('manufacture_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('images', models.ImageField(upload_to='mobiles/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
