# Generated by Django 4.0.4 on 2022-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_order_user_product_isorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
